# Source default setting
[ -f /etc/bashrc ] && . /etc/bashrc

# User environment PATH
PATH="$HOME/.local/bin:$HOME/bin:$PATH"
export GAUSSHOME="/home/opengauss/openGauss/install"
export BINARYLIBS="/home/opengauss/binarylibs"
export GCC_PATH="$BINARYLIBS/buildtools/gcc7.3/"
export CC="$GCC_PATH/gcc/bin/gcc"
export CXX="$GCC_PATH/gcc/bin/g++"
export LD_LIBRARY_PATH="$GAUSSHOME/lib:$GCC_PATH/gcc/lib64:$GCC_PATH/isl/lib:$GCC_PATH/mpc/lib/:$GCC_PATH/mpfr/lib/:$GCC_PATH/gmp/lib/:$LD_LIBRARY_PATH"
export PATH="/usr/local/go/bin:$GAUSSHOME/bin:$GCC_PATH/gcc/bin:$PATH"
export PGPORT=5433
